name: CI

on:
  push:
    branches: [main]
  pull_request: {}

permissions:
  contents: read
  code-quality: write

jobs:
  typecheck:
    runs-on: gha-ci-runners
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/typecheck

  test:
    runs-on: gha-ci-runners
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: ./.github/actions/test

  test-minimal-install:
    runs-on: gha-ci-runners
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-minimal-install
